src/objects/Country_Descriptor__c.object
<CustomObject>
    <description>Descriptor object used to map text representative inputs of countries to parent Standardized Country records for translative mapping.</description>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>Textual descriptor for the parent Standardized Country. Any record on an object enabled for mapping which has this value in it&apos;s country field will be updated to the standardized value chosen by the organizations preferences.</inlineHelpText>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Standardized_Country__c</fullName>
        <label>Standardized Country</label>
        <referenceTo>Standardized_Country__c</referenceTo>
        <relationshipLabel>Country Descriptors</relationshipLabel>
        <relationshipName>Country_Descriptors</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Country Descriptor</label>
    <nameField>
        <displayFormat>CD-{00000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Country Descriptors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CountryConfig__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <label>Country Mapping Config</label>
</CustomObject>

src/objects/CountryFieldSet__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Custom setting that controls which country fields to map.</description>
    <fields>
        <fullName>FieldName__c</fullName>
        <inlineHelpText>Enter the Name of the country field.</inlineHelpText>
        <label>Field Name</label>
        <length>200</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ObjectName__c</fullName>
        <label>Object Name</label>
        <length>200</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Country Field Set</label>
</CustomObject>

src/objects/Standardized_Country__c.object
<CustomObject>
    <description>Object container for ISO and or FIPS standardized country code. Used as a parent for non standard country descriptors.</description>
    <fields>
        <fullName>ISO_3166_1_alpha_2__c</fullName>
        <label>ISO 3166-1 alpha-2</label>
        <length>2</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ISO_3166_1_alpha_3__c</fullName>
        <label>ISO 3166-1 alpha-3</label>
        <length>3</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ISO_3166_1_numeric__c</fullName>
        <label>ISO 3166-1 numeric</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Standardized Country</label>
    <nameField>
        <label>ISO Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Standardized Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CountryMappingHelperUtilTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class CountryMappingHelperUtilTest {

    static testMethod void testStandardizeCountry() {
        System.assert(setUpTest());
        String inputCountry = 'United States';
        Account a = new Account(Name='ABC Company',BillingCountry=inputCountry);
        insert a;
        List<Account> accountList = new List<Account>{a};
        List<CountryFieldSet__c> settings = new List<CountryFieldSet__c>([SELECT Id,Name,ObjectName__c,FieldName__c FROM CountryFieldSet__c WHERE ObjectName__c = 'Account']);
        CountryMappingHelperUtil.standardizeCountries(accountList, settings);
        System.debug(accountList[0]);
        System.assertNotEquals(CountryMappingHelperUtil.outputCache, null);
    }
    
    static testMethod void testStandardizeCountryPassingNull() {
    	System.assert(setUpTest());
    	List<CountryFieldSet__c> settings = new List<CountryFieldSet__c>([SELECT Id,Name,ObjectName__c,FieldName__c FROM CountryFieldSet__c WHERE ObjectName__c = 'Account']);
        CountryMappingHelperUtil.standardizeCountries(null, settings);
        System.assertEquals(CountryMappingHelperUtil.outputCache, null);
    }
    
    static Boolean setUpTest() {
    	CountryFieldSet__c setting = new CountryFieldSet__c(Name='Account Billing Country',ObjectName__c='Account',FieldName__c='BillingCountry');
    	insert setting;
    	CountryConfig__c config = new CountryConfig__c(Name='Settings',Selected_Output__c='ISO_3166_1_alpha_3__c',Fuzzy_Match_Enabled__c=true);
    	insert config;
    	Standardized_Country__c stdCountry = new Standardized_Country__c(Name='United States',ISO_3166_1_alpha_2__c='US',ISO_3166_1_alpha_3__c='USA',ISO_3166_1_numeric__c='530');
    	insert stdCountry;
    	Country_Descriptor__c cDesc = new Country_Descriptor__c(Standardized_Country__c=stdCountry.Id,Description__c='United States');
    	insert cDesc;
    	return true;
    }
}