src/objects/Country_Descriptor__c.object
<CustomObject>
    <description>Descriptor object used to map text representative inputs of countries to parent Standardized Country records for translative mapping.</description>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>Textual descriptor for the parent Standardized Country. Any record on an object enabled for mapping which has this value in it&apos;s country field will be updated to the standardized value chosen by the organizations preferences.</inlineHelpText>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Standardized_Country__c</fullName>
        <label>Standardized Country</label>
        <referenceTo>Standardized_Country__c</referenceTo>
        <relationshipLabel>Country Descriptors</relationshipLabel>
        <relationshipName>Country_Descriptors</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Country Descriptor</label>
    <nameField>
        <displayFormat>CD-{00000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Country Descriptors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Standardized_Country__c.object
<CustomObject>
    <description>Object container for ISO and or FIPS standardized country code. Used as a parent for non standard country descriptors.</description>
    <fields>
        <fullName>FIPS_10_4__c</fullName>
        <label>FIPS 10-4</label>
        <length>2</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ISO_3166_1_alpha_2__c</fullName>
        <label>ISO 3166-1 alpha-2</label>
        <length>2</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ISO_3166_1_alpha_3__c</fullName>
        <label>ISO 3166-1 alpha-3</label>
        <length>3</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ISO_3166_1_numeric__c</fullName>
        <label>ISO 3166-1 numeric</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Standardized Country</label>
    <nameField>
        <label>ISO Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Standardized Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PostInstallAsynchProcessor.cls
/**
 *	@author: Shawn Butterfield, Salesforce.com Inc.
 *	This class is called from an Installation Context Adapter to automatically create some standardized 'out-of-the-box' Country Mappings
 */
public virtual class PostInstallAsynchProcessor {
	
	private static String endpoint = 'http://api.edoceo.com/iso/3166/1?f=json';
	
	@future(Callout=true)
	public static void setCountryMappings() {
		if(endpoint != null && !RuntimeState.isInFutureContext) {
			RuntimeState.isInFutureContext = true;
			List<CountryMapping> countries = parseResponse(getCountries());
			if(countries != null && countries.size() > 1) {
				List<Standardized_Country__c> stdCountriesToInsert = new List<Standardized_Country__c>();
				Map<String, String> codeDesc = new Map<String, String>();
				for(CountryMapping c : countries) {
					stdCountriesToInsert.add(new Standardized_Country__c(ISO_3166_1_numeric__c = c.code, ISO_3166_1_alpha_3__c = c.iso3, ISO_3166_1_alpha_2__c = c.iso2));
					codeDesc.put(c.code,c.name_en);
				}
				List<Database.SaveResult> sr;
				try{
					sr = Database.insert(stdCountriesToInsert, true);
				}
				catch(DMLException d) {
					System.debug(LoggingLevel.ERROR,'Error while trying to insert Standardized Countries, cannot continue. ' +d.getStackTraceString());
					return;
				}
				Set<Id> scRows;
				if(sr != null) {
					scRows = new Set<Id>();
					for(Database.SaveResult r : sr) {
						if(r.isSuccess()) {
							scRows.add(r.getId());
						}
					}
				}
				
				List<Standardized_Country__c> stdCountries;
				if(scRows != null) {
					 stdCountries = new List<Standardized_Country__c>([Select s.Id, s.Name, s.ISO_3166_1_numeric__c, s.ISO_3166_1_alpha_3__c, s.ISO_3166_1_alpha_2__c, s.FIPS_10_4__c From Standardized_Country__c s Where Id IN :scRows]);
				}
				
				List<Country_Descriptor__c> descList;
				if(stdCountries != null) {
					descList = new List<Country_Descriptor__c>();
					for(Standardized_Country__c c : stdCountries) {
						System.debug('std country in iterable: ' +c);
						String descriptor = codeDesc.get(c.ISO_3166_1_numeric__c);
						descList.add(new Country_Descriptor__c(Standardized_Country__c = c.Id, Description__c = descriptor));
					}
				}
				
				if(descList != null) {
					try {
						Database.insert(descList, true);
					}
					catch(DMLException d) {
						System.debug('Error while trying to insert Country_Descriptors, exiting gracefully ' +d.getStackTraceString());
					}
				}
			}
			else {
				System.debug(LoggingLevel.ERROR,'Fatal Error: Could not create any sample country mappings, didn not receive anything from the parser!');
			}
		}
	}
	
	private static HttpResponse getCountries() {
		HttpRequest req = createRequest(endpoint, null, 'GET', false, 20000);
		HttpResponse res;
		if(req != null) {
			Http http = new Http();
			res = new HttpResponse();
			try {
				res = http.send(req);
			}
			catch (Exception e) {
				System.debug(LoggingLevel.ERROR,'Exception making callout: ' +e.getStackTraceString());
			}
		}
		return res;
	}
	
	private static List<CountryMapping> parseResponse(HTTPResponse res) {
		List<CountryMapping> countries;
		if(res != null) {
			String jsonContent = res.getBody();
			if(jsonContent.countMatches('}') > 0) {
				// JSON from the standard API sucks, we have to fix it first before the Apex parser will eat it.
				jsonContent = jsonContent.replaceAll('(\\})', '},');
				jsonContent = jsonContent.replaceAll('(\\},\\])', '}]');
				System.debug('Json content \n ' +jsonContent);
			}
			JSONParser parser = JSON.createParser(jsonContent);
			countries = new List<CountryMapping>();
			while(parser.nextToken() != null) {
				if(parser.getCurrentToken() == JSONToken.START_ARRAY) {
					while(parser.nextToken() != null) {
						if(parser.getCurrentToken() == JSONToken.START_OBJECT) {
							CountryMapping country = (CountryMapping)parser.readValueAs(CountryMapping.class);
							String s = JSON.serialize(country);
							countries.add(country);
						}
					}
				}
			}
		}
		return countries;
	}
	
	/**
	 * Safely creates an http request
	 */
	private static HttpRequest createRequest(String url, String body, String method, Boolean compressed, Integer timeout) {
        if (url == null) {
            return null;
        }
        
        HttpRequest req = new HttpRequest();
        req.setEndpoint(url);
        
        if (body != null) {
            req.setBody(body);
        }
        
        // NOTE: Method is case sensitive.
        if ('GET'.equals(method) || 'POST'.equals(method)) {
            req.setMethod(method);
        }
        else {
            req.setMethod('GET');
        }
        
        if (compressed != null) {
            req.setCompressed(compressed);
        }
        
        // HttpRequest allows a timeout value between 1ms and 60000ms.
        if (timeout != null && timeout > 0 && timeout <= 60000) {
            req.setTimeout(timeout);
        }
        
        return req;
    }
}