src/objects/Country_Descriptor__c.object
<CustomObject>
    <description>Descriptor object used to map text representative inputs of countries to parent Standardized Country records for translative mapping.</description>
    <fields>
        <fullName>Standardized_Country__c</fullName>
        <label>Standardized Country</label>
        <referenceTo>Standardized_Country__c</referenceTo>
        <relationshipLabel>Country Descriptors</relationshipLabel>
        <relationshipName>Country_Descriptors</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Country Descriptor</label>
    <nameField>
        <displayFormat>CD-{00000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Country Descriptors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Standardized_Country__c.object
<CustomObject>
    <description>Object container for ISO and or FIPS standardized country code. Used as a parent for non standard country descriptors.</description>
    <label>Standardized Country</label>
    <nameField>
        <label>ISO Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Standardized Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PostInstallAdapter.cls
/**
 *	@author: Shawn Butterfield, Salesforce.com Inc.
 *	Installation adapter class implements the InstallHandler interface and runs a post installation script to fire an asynchronous process and populate Country mapping data to:
 *	Standardized_Country__c && Country_Descriptor__c
 *	Uses http://api.edoceo.com/iso/3166/1?f=json
 */
global class PostInstallAdapter implements InstallHandler {
	
	global Boolean success;
	
	global void onInstall(InstallContext context) {
		if(context.previousVersion() == null) {
			PostInstallAsynchProcessor.setCountryMappings();
			User u = [Select Id, Email from User where Id =:context.installerID()];   
			String toAddress= u.Email;
			String[] toAddresses = new String[]{toAddress};
			Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
			mail.setToAddresses(toAddresses);
			mail.setReplyTo('support@salesforce.com');
			mail.setSenderDisplayName('Package Support');
			mail.setSubject('Post-Install script ran successfully');
			mail.setPlainTextBody('Post-Install script created 249 country mappings for you.');
			Messaging.sendEmail(new Messaging.Email[] { mail });
			success = true;
		}
		else {
			// Upgrading or re-installing, do nothing.
		}
	}
}